CREATE DATABASE exercicio26Agosto;
use exercicio26Agosto;

CREATE TABLE IF NOT EXISTS FORNECEDOR (
IDFORNECEDOR INT  auto_increment NOT NULL,
NOME VARCHAR(45),
ENDERECO VARCHAR(45),
TELEFONE INT,
CIDADE VARCHAR(20) DEFAULT 'SÃO PAULO',
EMAIL VARCHAR(25) UNIQUE,
PRIMARY KEY (IDFORNECEDOR)
);